// <auto-generated />
using System;
using CleanArchitecture.PracticalTest.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanArchitecture.PracticalTest.Infrastructure.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20260307213311_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitecture.PracticalTest.Domain.Entidades.HistorialPaqueteEstatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaDeCambioEstado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_de_cambio_estado");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("PaqueteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paquete_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_historial_paquete_estatus");

                    b.HasIndex("PaqueteId")
                        .HasDatabaseName("ix_historial_paquete_estatus_paquete_id");

                    b.ToTable("historial_paquete_estatus", (string)null);
                });

            modelBuilder.Entity("CleanArchitecture.PracticalTest.Domain.Entidades.Paquete", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Altura")
                        .HasColumnType("numeric")
                        .HasColumnName("altura");

                    b.Property<decimal>("Ancho")
                        .HasColumnType("numeric")
                        .HasColumnName("ancho");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("Estatus")
                        .HasColumnType("integer")
                        .HasColumnName("estatus");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("numeric")
                        .HasColumnName("longitud");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric")
                        .HasColumnName("peso");

                    b.Property<Guid?>("RutaId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruta_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_paquetes");

                    b.HasIndex("RutaId")
                        .HasDatabaseName("ix_paquetes_ruta_id");

                    b.ToTable("paquetes", (string)null);
                });

            modelBuilder.Entity("CleanArchitecture.PracticalTest.Domain.Entidades.Ruta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destino");

                    b.Property<decimal>("DistanciaEnKm")
                        .HasColumnType("numeric")
                        .HasColumnName("distancia_en_km");

                    b.Property<decimal>("HorasEstimadas")
                        .HasColumnType("numeric")
                        .HasColumnName("horas_estimadas");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("origen");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_rutas");

                    b.ToTable("rutas", (string)null);
                });

            modelBuilder.Entity("CleanArchitecture.PracticalTest.Domain.Entidades.HistorialPaqueteEstatus", b =>
                {
                    b.HasOne("CleanArchitecture.PracticalTest.Domain.Entidades.Paquete", null)
                        .WithMany("Historial")
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historial_paquete_estatus_paquete_paquete_id");
                });

            modelBuilder.Entity("CleanArchitecture.PracticalTest.Domain.Entidades.Paquete", b =>
                {
                    b.HasOne("CleanArchitecture.PracticalTest.Domain.Entidades.Ruta", "Ruta")
                        .WithMany()
                        .HasForeignKey("RutaId")
                        .HasConstraintName("fk_paquetes_ruta_ruta_id");

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("CleanArchitecture.PracticalTest.Domain.Entidades.Paquete", b =>
                {
                    b.Navigation("Historial");
                });
#pragma warning restore 612, 618
        }
    }
}
